# Simple docker-compose.yml
# You can change your port or volume location

version: '3.8'
services:
  bot:
    build: .
    restart: always
    environment:
      - PROD=true
    depends_on:
      - db
  db:
    image: mariadb:11-jammy
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${SQLRoot}
      - MARIADB_USER=${SQLUser}
      - MARIADB_PASSWORD=${SQLUserPass}
      - MARIADB_DATABSE=SophiePowers
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - '3306:3306'

volumes:
  db_data: